steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'asia-south2-docker.pkg.dev/project-001-v1/docker-central/portfolio:$COMMIT_SHA'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'asia-south2-docker.pkg.dev/project-001-v1/docker-central/portfolio:$COMMIT_SHA'
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - '--image'
      - 'asia-south2-docker.pkg.dev/project-001-v1/docker-central/portfolio:$COMMIT_SHA'
      - '--region'
      - $_DEPLOY_REGION
      - '--platform'
      - $_PLATFORM
    entrypoint: gcloud
timeout: 1200s
images:
  - 'asia-south2-docker.pkg.dev/project-001-v1/docker-central/portfolio:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
serviceAccount: '659243537741@cloudbuild.gserviceaccount.com'
